/** 采购清单 */

/** 入厂记录 */
export const UPDATE_ADMIT_MODEL = 'UPDATE_ADMIT_MODEL';
export const FETCH_ADMIT_DATA = 'FETCH_ADMIT_DATA';
export const FILTER_PURCHASE_LIST = 'FILTER_PURCHASE_LIST';
export const UPDATE_ADMIT_REQUEST_STATUS = 'UPDATE_ADMIT_REQUEST_STATUS';
export const UPDATE_ADMIT_PRESENTATION_TYPE = 'UPDATE_ADMIT_PRESENTATION_TYPE';