module.exports = {
  SOPBusinessObjectType: new Map([[1, 'mBom中的工序']]),
  SOPFieldType: new Map([
    [1, '文本'],
    [2, '数字'],
    [3, '时间'],
    [4, '文件'],
    [5, '用户'],
    [6, '工位'],
    [10, '设备'],
    [11, '多用户'],
  ]),
  FIELD_TYPE_TEXT: 1,
  FIELD_TYPE_NUMBER: 2,
  FIELD_TYPE_TIME: 3,
  FIELD_TYPE_FILE: 4,
  FIELD_TYPE_USER: 5,
  FIELD_TYPE_WORKSTATION: 6,
  FIELD_TYPE_DEVICE: 10,
  FIELD_TYPE_MULTIPLE_USER: 11,
  SopControlProperty: new Map([[1, '显示'], [2, '输入']]),
  PROPERTY_SHOW: 1,
  PROPERTY_INPUT: 2,
  SopControlType: new Map([
    [1, '文本'],
    [2, '数字'],
    [3, '时间'],
    [4, '文件'],
    [5, '用户'],
    [6, '身份认证'],
    [7, '投产'],
    [8, '产出'],
    [9, '称量'],
    [10, '收料投产'],
    [11, '物料转移'],
    [12, '工位'],
    [13, '设备'],
    [14, 'AGV叫车'],
    [15, '虚拟投产'],
    [16, '虚拟产出'],
    [17, '虚拟物料转移'],
    [18, '虚拟收料投产'],
    [19, '报表'],
    [20, '多用户身份认证'],
  ]),
  SOP_CONTROL_TYPE_USER: 5,
  SOP_CONTROL_TYPE_AUTH: 6,
  TYPE_TEXT: 1,
  TYPE_NUMBER: 2,
  TYPE_TIME: 3,
  TYPE_FILE: 4,
  TYPE_USER: 5,
  TYPE_AUTH: 6,
  TYPE_INPUT: 7,
  TYPE_OUTPUT: 8,
  TYPE_WEIGHING: 9,
  TYPE_RECEIVE_SCAN: 10,
  TYPE_MATERIAL_LOT_TRANSFER: 11,
  TYPE_WORKSTATION: 12,
  TYPE_DEVICE: 13,
  TYPE_AGV: 14,
  TYPE_VIRTUAL_INPUT: 15,
  TYPE_VIRTUAL_RECEIVE_SCAN: 16,
  TYPE_VIRTUAL_OUTPUT: 17,
  TYPE_VIRTUAL_MATERIAL_LOT_TRANSFER: 18,
  TYPE_REPORT: 19,
  TYPE_MULTIPLE_USER: 20,
  SopControlInputTextType: new Map([[1, '单选框'], [2, '单行文本'], [3, '多行文本'], [4, '多选框']]),
  INPUT_TEXT_CHECKBOX: 1,
  INPUT_TEXT_SINGLE: 2,
  INPUT_TEXT_MULTIPLE: 3,
  INPUT_TEXT_CHECKBOX_MULTIPLE: 4,
  SopControlShowLogic: new Map([
    [1, '业务字段'],
    [2, '固定值'],
    [3, '固定文件'],
    [4, '固定用户'],
    [5, '系统当前时间'],
    [6, 'trigger公式'],
  ]),
  LOGIC_BUSINESS: 1,
  LOGIC_FIXED_VALUE: 2,
  LOGIC_FIXED_FILE: 3,
  LOGIC_FIXED_USER: 4,
  LOGIC_NOW_TIME: 5,
  LOGIC_TRIGGER: 6,
  NextLogic: {
    0: '无',
    1: '下个步骤',
    2: '人工选择',
    3: '条件判断',
  },
  NEXT_LOGIC_NONE: 0,
  NEXT_LOGIC_NEXT: 1,
  NEXT_LOGIC_PERSON_SELECT: 2,
  NEXT_LOGIC_IF_JUDGE: 3,
  INPUT_STANDARD_LOGIC_FIXED: 0,
  INPUT_STANDARD_LOGIC_DIY: 1,
  BETWEEN: 0,
  LT: 1,
  GT: 2,
  EQ: 3,
  LTE: 4,
  GTE: 5,
  TOLERANCE: 8,
  SopFieldRwPermissionMap: new Map([[0, '只读'], [1, '可读写']]),
  SOP_FIELD_READONLY: 0,
  SOP_FIELD_READWRITE: 1,
  SOPStatus: new Map([[0, '停用中'], [1, '启用中']]),
  SOP_DISABLED_STATUS: 0,
  SOP_ENABLED_STATUS: 1,
  SopStepPrivilegeType: new Map([[1, '用户'], [2, '用户类型字段'], [3, '角色'], [4, '用户组']]), // 签名权限
  SOP_STEP_PRIVILEGE_TYPE_USER: 1,
  SOP_STEP_PRIVILEGE_TYPE_USERTYPE: 2,
  SOP_STEP_PRIVILEGE_TYPE_ROLE: 3,
  SOP_STEP_PRIVILEGE_TYPE_USER_GROUP: 4,
  SopStepGroupType: new Map([[1, '串行'], [2, '并行']]),
  SOP_STEP_GROUP_TYPE_SERIAL: 1,
  SOP_STEP_GROUP_TYPE_PARALLEL: 2,
  SOP_STEP_TYPE_STEP: 1, // 步骤
  SOP_STEP_TYPE_GROUP: 2, // 步骤组
  FIFO_VALIDITY_PERIOD: 1, // 有效期
  FIFO_INBOUND_BATCH: 2, // 入厂批次
  FIFO_CREATE_TIME: 3, // 产出时间
  FIFO_RULES: new Map([[1, '有效期'], [2, '入厂批次'], [3, '产出时间']]),
  CREATE_BY_SOP_TEMPLATE: 'SOP_MODE_TEMPLATE',
  EDIT_BY_SOP_TEMPLATE: 'SOP_MODE_EDIT_TEMPLATE',
};
