const FETCH_LIST_SUCCESS = 'QC_DATA/FETCH_TABLE_LIST_SUCCESS'
const FETCH_LIST_FAIL = 'QC_DATA/FETCH_TABLE_LIST_FAIL'
const FETCH_LIST_REQUEST = 'QC_DATA/FETCH_LIST_REQUEST'
const CREATE_DATA_REQUEST = 'QC_DATA/CREATE_DATA_REQUEST'
const CREATE_DATA_SUCCESS = 'QC_DATA/CREATE_DATA_SUCCESS'
const CREATE_DATA_FAIL = 'QC_DATA/CREATE_DATA_FAIL'
const UPDATE_DATA_REQUEST = 'QC_DATA/UPDATE_DATA_REQUEST'
const UPDATE_DATA_SUCCESS = 'QC_DATA/UPDATE_DATA_SUCCESS'
const UPDATE_DATA_FAIL = 'QC_DATA/UPDATE_DATA_FAIL'
const DELETE_DATA_REQUEST = 'QC_DATA/DELETE_DATA_REQUEST'
const DELETE_DATA_SUCCESS = 'QC_DATA/DELETE_DATA_SUCCESS'
const DELETE_DATA_FAIL = 'QC_DATA/DELETE_DATA_FAIL'
const FETCH_MORE_LIST_REQUEST = 'QC_DATA/FETCH_MORE_LIST_REQUEST'
const FETCH_MORE_LIST_SUCCESS = 'QC_DATA/FETCH_MORE_LIST_SUCCESS'
const CHANGE_SETTINGS_SUCCESS = 'QC_DATA/CHANGE_SETTINGS_SUCCESS'
const FETCH_LOG_LIST_REQUEST = 'QC_DATA/FETCH_LOG_LIST_REQUEST'
const FETCH_LOG_LIST_FAIL = 'QC_DATA/FETCH_LOG_LIST_FAIL'
const FETCH_LOG_LIST_SUCCESS= 'QC_DATA/FETCH_LOG_LIST_SUCEESS'
export {
    FETCH_LIST_SUCCESS,
    FETCH_LIST_FAIL,
    FETCH_LIST_REQUEST,
    CREATE_DATA_REQUEST,
    CREATE_DATA_SUCCESS,
    CREATE_DATA_FAIL,
    UPDATE_DATA_REQUEST,
    UPDATE_DATA_SUCCESS,
    UPDATE_DATA_FAIL,
    DELETE_DATA_REQUEST,
    DELETE_DATA_SUCCESS,
    DELETE_DATA_FAIL,
    FETCH_MORE_LIST_SUCCESS,
    CHANGE_SETTINGS_SUCCESS,
    FETCH_LOG_LIST_REQUEST,
    FETCH_LOG_LIST_SUCCESS,
    FETCH_LOG_LIST_FAIL,
    FETCH_MORE_LIST_REQUEST,
}