const FETCH_WILL_COME_LIST_SUCCESS = 'OUT_PART/FETCH_WILL_COME_DATA_SUCCESS'
const FETCH_WILL_COME_LIST_FAIL = 'OUT_PART/FETCH_WILL_COME_DATA_FAIL'
const FETCH_WILL_COME_LIST_REQUEST = 'OUT_PART/FETCH_WILL_COME_DATA_REQUEST'
const FETCH_WAREHOUSE_LIST_SUCCESS = 'OUT_PART/FETCH_WAREHOUSE_LIST_SUCCESS'
const CHANGE_SETTINGS_SUCCESS = 'OUT_PART/CHANGE_TABLE_SETTINGS_SUCCESS'
const GET_WAREHOUSE_LIST = 'OUT_PART/GET_WAREHOUSE_LIST'
export {
    FETCH_WILL_COME_LIST_SUCCESS,
    FETCH_WILL_COME_LIST_FAIL,
    FETCH_WILL_COME_LIST_REQUEST,
    CHANGE_SETTINGS_SUCCESS,
    GET_WAREHOUSE_LIST,
    FETCH_WAREHOUSE_LIST_SUCCESS
}