const eventTypes = {
  CREATE_PRODUCT_ORDER: {
    value: 'create_product_order',
    display: '创建productOrder',
    level: 1,
    title: '任务协同',
    resourceType: 'productOrder',
  },
  ASSIGN_PROD_TASK: {
    value: 'assign_prod_task',
    display: '你收到一个任务',
    level: 1,
    title: '任务协同',
    resourceType: 'task',
  },
  NOTIFY_PROD_TASK_OPERATOR: {
    value: 'notify_prod_task_operator',
    display: '派发生产任务',
    level: 1,
    title: '任务协同',
    resourceType: 'task',
  },
  ASSIGN_QC_TASK: {
    value: 'assign_qc_task',
    display: '你收到一个任务',
    level: 1,
    title: '任务协同',
    resourceType: 'qcTask',
  },
  START_PROD_TASK: {
    value: 'start_prod_task',
    display: '开始生产任务',
    level: 1,
    title: '生产管理',
    resourceType: 'task',
  },
  FINISH_PROD_TASK: {
    value: 'finish_prod_task',
    display: '完成生产任务',
    level: 1,
    title: '生产管理',
    resourceType: 'task',
  },
  START_QC_TASK: {
    value: 'start_qc_task',
    display: '开始质检任务',
    level: 1,
    title: '质量管理',
    resourceType: 'qcTask',
  },
  FINISH_QC_TASK: {
    value: 'finish_qc_task',
    display: '完成质检任务',
    level: 1,
    title: '质量管理',
    resourceType: 'qcTask',
  },
  LG_TRANSFER_IN: {
    value: 'lg_transfer_in',
    display: '扫描入库',
    level: 1,
    title: '物流管理',
    resourceType: 'logistics',
  },
  LG_TRANSFER_OUT: {
    value: 'lg_transfer_out',
    display: '扫描出库',
    level: 1,
    title: '物流管理',
    resourceType: 'logistics',
  },
  ASSIGN_LG_TASK: {
    value: 'assign_lg_task',
    display: '派发物流任务',
    level: 1,
    title: '任务协同',
    resourceType: 'lgTask',
  },
  SCHEDULE_PROD_TASK: {
    value: 'schedule_prod_task',
    display: '任务已到开始时间',
    level: 1,
    title: '任务协同',
    resourceType: 'task',
  },
  RESCHEDULE_PROD_TASK: {
    value: 'reschedule_prod_task',
    display: '任务开始时间已调整',
    level: 1,
    title: '任务协同',
    resourceType: 'task',
  },
  UN_ASSIGN_PROD_TASK: {
    value: 'un_assign_prod_task',
    display: '任务已开始，无人领取',
    level: 1,
    title: '任务协同',
    resourceType: 'task',
  },
  RE_ASSIGN_PROD_TASK: {
    value: 'reassign_prod_task',
    display: '任务已被重新分配',
    level: 1,
    title: '任务协同',
    resourceType: 'task',
  },
  CANCEL_PROD_TASK: {
    value: 'cancel_prod_task',
    display: '任务已被取消',
    level: 1,
    title: '任务协同',
    resourceType: 'task',
  },
  SCHEDULE_QC_TASK: {
    value: 'schedule_qc_task',
    display: '任务已到开始时间',
    level: 1,
    title: '质量管理',
    resourceType: 'qcTask',
  },
  RESCHEDULE_QC_TASK: {
    value: 'reschedule_qc_task',
    display: '任务开始时间已调整',
    level: 1,
    title: '质量管理',
    resourceType: 'qcTask',
  },
  RE_ASSIGN_QC_TASK: {
    value: 're_assign_qc_task',
    display: '任务已被重新分配',
    level: 1,
    title: '质量管理',
    resourceType: 'qcTask',
  },
  UN_ASSIGN_QC_TASK: {
    value: 'un_assign_qc_task',
    display: '任务已开始，无人领取',
    level: 1,
    title: '质量管理',
    resourceType: 'qcTask',
  },
};

export default eventTypes;
